fos_rest:
  routing_loader:
    default_format: html
    include_format: true

  format_listener:
    enabled: true
    rules:
    - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
    - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }

  param_fetcher_listener: true

  view:
    view_response_listener: true