###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: the-rick-and-morty-rick-and-the-morty-api-webserver
      working_dir: /rick-and-the-morty-api
      volumes:
          - .:/rick-and-the-morty-api
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: the-rick-and-morty-rick-and-the-morty-api-php-fpm
      working_dir: /rick-and-the-morty-api
      volumes:
        - .:/rick-and-the-morty-api
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

